/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./components/common/ActivityCard.vue')['default']
    ActivityInfoCard: typeof import('./components/common/ActivityInfoCard.vue')['default']
    AdminSidebar: typeof import('./components/layout/AdminSidebar.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    BottomNav: typeof import('./components/layout/BottomNav.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    GlassModal: typeof import('./components/common/GlassModal.vue')['default']
    MyActivityCard: typeof import('./components/common/MyActivityCard.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    ParticipationCard: typeof import('./components/common/ParticipationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
